API links updated to new model names
ImperialCollegeLondon/virtual_rainforest pull request #177
Opened 2023-02-13 10:52 UTC by vgro

# Description

We recently updated the model names from `model.py` to `{MODEL_NAME}_model.py`. In the process, we missed updating the docs which I've done here.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [x] Bug fix (non-breaking change which fixes an issue)

## Key checklist

- [x] Make sure you've run the `pre-commit` checks: `$ pre-commit run -a`
- [x] All tests pass: `$ poetry run pytest`

## Further checks

- [NA] Code is commented, particularly in hard-to-understand areas
- [NA] Tests added that prove fix is effective or that feature works

2023-02-13 10:56 UTC, davidorme commented
Do you want to add the `core/model.py` rename and close #178 😄

2023-02-13 11:10 UTC, jacobcook1995 requested changes
Noticed a few broken links, also as David mentioned `model.py` should be renamed to `base_model.py` as part of this pull request

2023-02-13 11:10 UTC, jacobcook1995 commented on docs/source/api/abiotic/abiotic_model.md
>  # API documentation for the {mod}`~virtual_rainforest.models.abiotic.model` module
This link should change as well

2023-02-13 11:10 UTC, jacobcook1995 commented on docs/source/api/core.md
> +* The {mod}`~virtual_rainforest.core.base_model` submodule provides an Abstract
This link breaks because `model.py` hasn't yet been renamed to `base_model.py`

2023-02-13 11:10 UTC, jacobcook1995 commented on docs/source/api/core/base_model.md
>  # API documentation for the {mod}`~virtual_rainforest.core.model` module
This should also be updated to use `base_model` (once the renaming has happened)

2023-02-13 11:10 UTC, jacobcook1995 commented on docs/source/api/soil/soil_model.md
>  # API documentation for the {mod}`~virtual_rainforest.soil.model` module
This link should also be updated

2023-02-13 11:10 UTC, vgro commented
> @vgro Do you want to add the `core/model.py` rename and close #178 😄

I've already done that, please let me know if I missed something.

2023-02-13 11:12 UTC, jacobcook1995 commented
The change from `core/model.py` to `core/base_model.py` doesn't show up in the file changes for some reason?

2023-02-13 11:13 UTC, jacobcook1995 commented
Also some of the links in the module docstrings for `abiotic_model.py` and `soil_model.py` will have to change as they currently refer to `core/model`

2023-02-13 11:57 UTC, jacobcook1995 approved these changes
All works now apart from a minor problem in one of the module docstrings

2023-02-13 11:57 UTC, jacobcook1995 commented on virtual_rainforest/core/base_model.py
> +"""The :mod:`~virtual_rainforest.core.base_model`module provides a consistent API across
needs to be a space between base_model` and module here, otherwise the docstring doesn't render properly

2023-02-13 14:00 UTC, davidorme commented
@jacobcook1995 and I were just chatting about adding `nitpicky = True` to the `conf.py` file. 
https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-nitpicky

That should catch all of these issues when we run `build html`. @vgro Do you want to add that change to this PR? And possibly then the results of fixing broken links.

2023-02-13 14:02 UTC, davidorme commented
Although - having just run that - it also traps all the `xarray` and `numpy` refs, so we'd probably want to also fix #147 in this PR! I think that would fix it! That should be a fairly short addition to `docs/source/conf.py`.

2023-02-13 14:18 UTC, davidorme commented
I'm going to add a commit to this that turns on `nitpicky` and `intersphinx` - there are quite a few errors: sometimes a broken link, sometime e.g. a method using `:class:`.

2023-02-13 14:20 UTC, davidorme commented
And @alexdewar suggested we set up a GitHub Action to test the doc builds too, but that seems like another PR to me.

2023-02-13 14:30 UTC, davidorme commented
That's commit has given me a shortish list of fixes to make. Will whip through them.

2023-02-13 14:43 UTC, vgro commented
> That's commit has given me a shortish list of fixes to make. Will whip through them.

Hello and sorry, the website didn't update properly and I didn't see all you comments before I fixed the missing space. Can I leave these change to you @davidorme ?

2023-02-13 14:44 UTC, davidorme commented
That's fine - got your change. I think @jacobcook1995 is hunting some down too 😄

2023-02-13 14:46 UTC, vgro commented
> That's fine - got your change. I think @jacobcook1995 is hunting some down too 😄

I hadn't though about all the links when I started, it's surely good to put some checks in place that we don't have to do that manually in the future :-)

2023-02-14 10:29 UTC, jacobcook1995 commented
All the build warnings should now be fixed, I had to turn off nitpick for a few (external) classes because it seemed impossible to get them to link properly.
Fixes #178 
Fixes #147

2023-02-15 10:13 UTC, davidorme approved these changes
LGTM

2023-02-15 10:19 UTC, merged