Added handling of herbivory waste products to the litter model
ImperialCollegeLondon/virtual_rainforest pull request #583
Opened 2024-10-10 09:25 UTC by jacobcook1995

# Description

A previous PR (#577) added a flow from the animal model representing waste products from herbivory (e.g. an elephant pulls off a branch but doesn't eat it all and drops the remainder). This PR changes the litter model so that it actually does something with this type of flow (which at present only exists for leaves).

Getting this to work required restructuring of the litter model. Primarily by adding an `InputPartition` class, which collects all the steps needed to calculate the total input of each plant matter type as well as to calculate the split of each plant matter type between litter pools. This class returns an `InputDetails` dataclass which gets used by the rest of the `litter` model. Feedback on this restructure would be very helpful!

Fixes #510

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

## Key checklist

- [x] Make sure you've run the `pre-commit` checks: `$ pre-commit run -a`
- [x] All tests pass: `$ poetry run pytest`

## Further checks

- [x] Code is commented, particularly in hard-to-understand areas
- [x] Tests added that prove fix is effective or that feature works
- [ ] Relevant documentation reviewed and updated

2024-10-10 12:24 UTC, davidorme requested changes
I don't love the name `InputDetails` - it's a bit generic. `LitterInputs`? Asides from that I think the science all looks fine, but as I've noted in comments, the `InputPartition`/`InputDetails` implementation feels like a single class thats fallen in half.

2024-10-10 12:24 UTC, davidorme commented on virtual_ecosystem/models/litter/input_partition.py
> +    """
This feels structurally a bit odd - the `InputPartition` class really only exists as a factory method for `InputDetails` and as a thin wrapper around `Data`. I can think of two alternative structures:

* Make `Data` and `constants` as `InitVar` attributes to `InputDetails` and make all the rest of the attributes `field(init=False)`. Then all of the logic in `InputPartition` can be put into a `__post_init__` method for `InputDetails`.

* That does restrict you to only ever populating an instance of `InputDetails` using `Data`, which to be honest sounds like it is the only use case. But you could also have it as a factory class method on the current dataclass. You could then create an instance programatically from dicts of variables.

```python3
@dataclass
class InputDetails:
    ...
    
    @classmethod
    def create_from_data(cls, data: Data, constants: LitterConsts) -> InputDetails:
         ...
```
  You would also need to pass `Data` to `combine_input_sources` - that could then just be a standalone function.

2024-10-10 14:29 UTC, jacobcook1995 commented
@davidorme thanks for the feedback fully agree that the two separate classes were clunky so I have now merged them into one

2024-10-10 14:55 UTC, davidorme approved these changes
Yeah - that seems cleaner. I'd be tempted to rename the module though, since that class is now gone. Probably fine with `models/litter/inputs.py`?

2024-10-11 07:44 UTC, dalonsoa approved these changes
This looks good, and pretty clean to put all related stuff in its own class. My only comment is that you change the name of the class to `LitterInputs`, but let the variables as `input_details`. I'd change this to `litter_inputs` to be more explicit about what inputs we are talking about.

2024-10-11 07:44 UTC, dalonsoa commented on virtual_ecosystem/models/litter/inputs.py
> +@dataclass
If the `LitterInputs` objects are not to be modified after creation, make it frozen with `@dataclass(frozen=True)` to avoid mistakes.

2024-10-11 13:40 UTC, merged